/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

import enumeracije.ModForme;
import forme.stampanje.FormaPregledStampanja;
import forme.stampanje.FormaUnosStampanja;
import forme.masine.FormaPregledMasina;
import forme.masine.FormaUnosMasina;
import forme.narucivanje.FormaPregledNarucivanja;
import forme.narucivanje.FormaUnosNarucivanja;

/**
 *
 * @author Kosta
 */
public class FormaGlavna extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public FormaGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        meniMasine = new javax.swing.JMenu();
        meniItemPretragaMasina = new javax.swing.JMenuItem();
        meniItemSacuvajMasinu = new javax.swing.JMenuItem();
        meniNarucivanje = new javax.swing.JMenu();
        jMenuItemPregledNarucivanja = new javax.swing.JMenuItem();
        jmiUnosNarucivanja = new javax.swing.JMenuItem();
        meniStampanje = new javax.swing.JMenu();
        jmiPretragaStampanja = new javax.swing.JMenuItem();
        jmiUnosStampanja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");

        meniMasine.setText("Masine");

        meniItemPretragaMasina.setText("Pregled masina");
        meniItemPretragaMasina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniItemPretragaMasinaActionPerformed(evt);
            }
        });
        meniMasine.add(meniItemPretragaMasina);

        meniItemSacuvajMasinu.setText("Unos nove masine");
        meniItemSacuvajMasinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniItemSacuvajMasinuActionPerformed(evt);
            }
        });
        meniMasine.add(meniItemSacuvajMasinu);

        jMenuBar1.add(meniMasine);

        meniNarucivanje.setText("Narucivanje");

        jMenuItemPregledNarucivanja.setText("Pregled narucivanja");
        jMenuItemPregledNarucivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledNarucivanjaActionPerformed(evt);
            }
        });
        meniNarucivanje.add(jMenuItemPregledNarucivanja);

        jmiUnosNarucivanja.setText("Unos narucivanja");
        jmiUnosNarucivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosNarucivanjaActionPerformed(evt);
            }
        });
        meniNarucivanje.add(jmiUnosNarucivanja);

        jMenuBar1.add(meniNarucivanje);

        meniStampanje.setText("Stampanje");

        jmiPretragaStampanja.setText("Pretraga stampanja");
        jmiPretragaStampanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaStampanjaActionPerformed(evt);
            }
        });
        meniStampanje.add(jmiPretragaStampanja);

        jmiUnosStampanja.setText("Unos stampanja");
        jmiUnosStampanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosStampanjaActionPerformed(evt);
            }
        });
        meniStampanje.add(jmiUnosStampanja);

        jMenuBar1.add(meniStampanje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meniItemPretragaMasinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniItemPretragaMasinaActionPerformed
        FormaPregledMasina pk = new FormaPregledMasina(this, true);
        pk.pack();
        pk.setVisible(true);
    }//GEN-LAST:event_meniItemPretragaMasinaActionPerformed

    private void meniItemSacuvajMasinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniItemSacuvajMasinuActionPerformed
        FormaUnosMasina uk = new FormaUnosMasina(this, true, null, ModForme.UNOS);
        uk.pack();
        uk.setVisible(true);
    }//GEN-LAST:event_meniItemSacuvajMasinuActionPerformed

    private void jmiPretragaStampanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaStampanjaActionPerformed
        FormaPregledStampanja ppd = new FormaPregledStampanja(this, true);
        ppd.pack();
        ppd.setVisible(true);
    }//GEN-LAST:event_jmiPretragaStampanjaActionPerformed

    private void jmiUnosStampanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosStampanjaActionPerformed
        FormaUnosStampanja upp = new FormaUnosStampanja(this, true);
        upp.pack();
        upp.setVisible(true);
    }//GEN-LAST:event_jmiUnosStampanjaActionPerformed

    private void jMenuItemPregledNarucivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledNarucivanjaActionPerformed
        FormaPregledNarucivanja pko =new FormaPregledNarucivanja(this, true);
        pko.pack();
        pko.setVisible(true);
    }//GEN-LAST:event_jMenuItemPregledNarucivanjaActionPerformed

    private void jmiUnosNarucivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosNarucivanjaActionPerformed
        FormaUnosNarucivanja unos = new FormaUnosNarucivanja(this, true);
        unos.pack();
        unos.setVisible(true);
    }//GEN-LAST:event_jmiUnosNarucivanjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPregledNarucivanja;
    private javax.swing.JMenuItem jmiPretragaStampanja;
    private javax.swing.JMenuItem jmiUnosNarucivanja;
    private javax.swing.JMenuItem jmiUnosStampanja;
    private javax.swing.JMenuItem meniItemPretragaMasina;
    private javax.swing.JMenuItem meniItemSacuvajMasinu;
    private javax.swing.JMenu meniMasine;
    private javax.swing.JMenu meniNarucivanje;
    private javax.swing.JMenu meniStampanje;
    // End of variables declaration//GEN-END:variables
}
