/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.narucivanje;

import domen.Stampanje;
import domen.IOpstiDomenskiObjekat;
import domen.Klijent;
import domen.Narucivanje;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Kosta
 */
public class FormaUnosNarucivanja extends javax.swing.JDialog {

    private Narucivanje n;
    private FormaPregledNarucivanja formaPregled;

    /**
     * Creates new form FormaUnosNarucivanja
     */
    public FormaUnosNarucivanja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniKomboKlijenata();
        popuniKomboStampanja();
        btnObrisi.setVisible(false);
        sakrijErrLabele();
    }

    public FormaUnosNarucivanja(java.awt.Frame parent, boolean modal, FormaPregledNarucivanja formaPregled) {
        this(parent, modal);
        this.formaPregled = formaPregled;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatumNarucivanja = new javax.swing.JTextField();
        cmbKlijent = new javax.swing.JComboBox();
        cmbStampanje = new javax.swing.JComboBox();
        btnSacuvaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        errDatum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datum narucivanja:");

        jLabel2.setText("Klijent:");

        jLabel3.setText("Stampanje:");

        cmbKlijent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbStampanje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        errDatum.setForeground(new java.awt.Color(204, 0, 0));
        errDatum.setText("datum mora biti u formatu dd.MM.yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatumNarucivanja)
                            .addComponent(cmbKlijent, 0, 296, Short.MAX_VALUE)
                            .addComponent(cmbStampanje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48)
                .addComponent(errDatum)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatumNarucivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errDatum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbStampanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnObrisi))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            String dat = txtDatumNarucivanja.getText();
            
            boolean valid = true;
            
            Date datum = null;
            try {
                datum = sdf.parse(dat);
                errDatum.setVisible(false);
            } catch (ParseException ex) {
                valid = false;
                errDatum.setVisible(true);                
            }
            Klijent k = (Klijent) cmbKlijent.getSelectedItem();
            Stampanje s = (Stampanje) cmbStampanje.getSelectedItem();
            
            if (!valid) {                
                return;
            }
            
            Narucivanje nar = new Narucivanje(1, datum, s, k);
            
            ServerskiOdgovor so = Kontroler.getInstance().sacuvajNarucivanje(nar);
            JOptionPane.showMessageDialog(this, so.getPoruka());
            zatvoriFormu();
        } catch (Exception ex) {
            Logger.getLogger(FormaUnosNarucivanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ServerskiOdgovor so = Kontroler.getInstance().obrisiNarucivanje(n);
        JOptionPane.showMessageDialog(this, so.getPoruka());
        formaPregled.pretrazi();
        zatvoriFormu();
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaUnosNarucivanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaUnosNarucivanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaUnosNarucivanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaUnosNarucivanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormaUnosNarucivanja dialog = new FormaUnosNarucivanja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbKlijent;
    private javax.swing.JComboBox cmbStampanje;
    private javax.swing.JLabel errDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDatumNarucivanja;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboKlijenata() {
        List<IOpstiDomenskiObjekat> lista = Kontroler.getInstance().dajListuKlijenata();
        cmbKlijent.removeAllItems();

        for (IOpstiDomenskiObjekat odo : lista) {
            cmbKlijent.addItem(odo);
        }
    }

    private void popuniKomboStampanja() {
        List<IOpstiDomenskiObjekat> lista = Kontroler.getInstance().dajListuStampanja();
        cmbStampanje.removeAllItems();

        for (IOpstiDomenskiObjekat odo : lista) {
            cmbStampanje.addItem(odo);
        }
    }

    void setFormuZaBrisanje(Narucivanje naru) {
        this.n = naru;
        btnObrisi.setVisible(true);
        btnSacuvaj.setVisible(false);
        txtDatumNarucivanja.setEditable(false);
        txtDatumNarucivanja.setText(new SimpleDateFormat("dd.MM.yyyy").format(naru.getDatumNarucivanja()));
        cmbStampanje.setSelectedItem(naru.getStampanje());
        cmbStampanje.setEnabled(false);
        cmbKlijent.setSelectedItem(naru.getKlijent());
        cmbKlijent.setEnabled(false);
    }

    private void zatvoriFormu() {
        this.setVisible(false);
        this.dispose();
    }

    private void sakrijErrLabele() {
        errDatum.setVisible(false);
    }
}
